### ISSUE TITLE
Exceptions are not caught in the error stream

### ISSUE THREAD

**Issue by mirichmo** [PowerShell/Remotely#4]

**Comment by daxian-dbw** [comment]
Repro Steps:
$result = remotely { throw "bad" }
$result.GetError()

Or
$result = remotely { Get-Command NonExist -ErrorAction Stop }
$result.GetError()

Expected: Capture the exception or terminating errors
Actual: Exception or terminating errors are not captured.

**Comment by adityapatwardhan** [comment]
Fixed the issue in merge request #10
