### ISSUE TITLE
If the remotely block returns $false or integer 0, then the value is lost

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/Remotely#7]
Repro Steps:
$result = Remotely { $false }
$result -eq $false

Expected: Comparison result should be True
Actual: Comparison result is False

$result = Remotely { 0 }
$result -eq 0

Expected: Comparison result should be True
Actual: Comparison result is False

**Comment by adityapatwardhan** [comment]
Resolved the issue with Merge request #9
